language: node_js
node_js:
  - '8'
before_script:
  - npm install -g grunt-cli
  - npm install -g npm@latest
notifications:
  hipchat:
    rooms:
      - secure: FMZA1rLmB7zmfg+8shfyEo2CgsRlWEZNbNOK5oaZRlrRv/6Uz1v21r7T5TzXvA+nxX+30bn8UFLVKHRXVjr6Zs1sGqMcpz5YoSVXDZ/ryFeoS6LKkEnvxbt/lfdD4kRDNUEjgGuRUiI6M0Sk+vg/w34WWwlC3tKC8y7sIMm8vH8=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> / <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
branches:
  only:
    - master
